### ISSUE TITLE
TypeError: Request scheme 'chrome-extension' is unsupported

### ISSUE THREAD

**Issue by adambyer** [praekelt/django-recaptcha#135]
Hi, I just set this up for the first time today and I'm getting the following error in Chrome developing locally...

```
Uncaught (in promise) TypeError: Request scheme 'chrome-extension' is unsupported
    at newtab-serviceworker.js:61
    at <anonymous>
(anonymous) @ newtab-serviceworker.js:61
newtab-serviceworker.js:61 
```

Otherwise, the captcha is there and appears to work. Any idea what that error is all about?

Thanks.

**Comment by adamchainz** [comment]
I think it's related to a broken Chrome extension and nothing to do with django-recaptcha

**Comment by adamchainz** [comment]
Unless you've set it otherwise, extensions are disabled in Incognito mode, try that and see if the error is still there
