### ISSUE TITLE
Recaptcha version

### ISSUE THREAD

**Issue by tityrus** [praekelt/django-recaptcha#140]
Google sent out a communication stating that support for the v1 recaptcha ends on 01/01/2017, ie tomorrow.

It seems like django-recaptcha uses this version 1. (from looking at the sourcecode, can anyone confirm this?)

Are there any plans to update to the v2 API?

**Comment by nikmolnar** [comment]
See #79 which seems to indicate that v2 is already supported with the `NOCAPTCHA = True` setting.

**Comment by nikmolnar** [comment]
It would be good to clarify this in the docs, however, since the current README says nothing about the v2 API and it's not readily apparent that v2 == NOCAPTCHA.

**Comment by jorisvd** [comment]
Thanks for your reply @nikmolnar !

More than updating the documentation, NOCAPTCHA=True should become the default, as the V1 is no longer supported since Nov 1.

**Comment by nikmolnar** [comment]
@jorisvd Yes, this is an excellent point!

**Comment by sixhobbits** [comment]
It would be good to see clarification in the readme about versions as there is now V3 too and it's not clear what is actually being used.

**Comment by AltusBarry** [comment]
As of version 2.0.0, the NOCAPTCHA setting has been deprecated and the default widget is the reCAPTCAH v2 Checkbox.

Unfortunately `NOCAPTCHA = True` is required by all versions of django-recaptcha pre version 2.0.0. This was not always evaluated as true, to ensure the behaviour of existing installations did no change.

If possible please consider upgrading to version 2.0.0+
