### ISSUE TITLE
Testing post requests with captcha

### ISSUE THREAD

**Issue by marksweb** [praekelt/django-recaptcha#150]
The testing examples show the form valid/invalid testing scenarios, but I'm working with a test suite that tests certain error messages & redirects so need to be able to post data to a URL.

With captcha fields now added to the forms on these URLs I'm just hitting form errors from the captcha field, so it is it not possible to fake the response from captcha for this purpose?

For example, I've got a test class (simplified);

```python
class TestApplicationLoginView(BaseTest, WebTest):
    def setUp(self):
        os.environ['RECAPTCHA_TESTING'] = 'True'

    def test_login_post(self):
        url = reverse(
            'vers:login',
            kwargs={'client_slug': self.client.slug}
        )
        response = self.app.post(
            url, params={
                'email': self.user.email,
                'password': self.password
            }
        )
        self.assertContains(response, 'Passwords do not match')
        response = self.app.post(
            url, params={
                'email': self.user.email,
                'password': self.password,
                'password2': self.password,
                'captcha_0': 'testing',
                'captcha_1': 'PASSED'
            }
        )
        self.assertRedirects(response, self.profile_redirect())

    def tearDown(self):
        del os.environ['RECAPTCHA_TESTING']
```

The result of this is an error in the form so the test fails on the grounds the response is a 200, not 302.

**Comment by marksweb** [comment]
Alright, so don't know why I got down the route of `captcha_0` and `captcha_1`, but testing with `'g-recaptcha-response': 'PASSED'` is all it needed.

**Comment by BigglesZX** [comment]
Apologies for posting on a closed issue but I ran into this problem today too – perhaps it would be helpful to add a note to the docs about using `'g-recaptcha-response': 'PASSED'` in POST requests when testing?
