### ISSUE TITLE
Django recaptcha with ajax mode is loading old js file

### ISSUE THREAD

**Issue by HoshiYamazaki** [praekelt/django-recaptcha#162]
I get this error:
> Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.

When importing recaptcha file:

> <script type="text/javascript" src="{% static 'js/recaptcha_ajax.js' %}"></script>
So I though I will see what is inside. And there is old Captcha v2 code:
```js
var RecaptchaState = {
    challenge : 'SHUTDOWN',
    timeout : 1800,
    lang : '',
    server : 'https://www.google.com/recaptcha/api/',
    site : 'SHUTDOWN',
    error_message : '',
    programming_error : '',
    is_incorrect : false,
    rtl : false,
    payload_url : 'https://www.gstatic.com/recaptcha/images/v1_unsupported.png'
};

document.write('<scr'+'ipt type="text/javascript" s'+'rc="' + RecaptchaState.server + 'js/recaptcha.js"></scr'+'ipt>');
```
I want to ask, how to repair this error and get AJAX mode working? Is there any JS file of Recaptcha v2 with compatibility of Django Recaptcha? Or should I use another package?

**Comment by HoshiYamazaki** [comment]
> Blocked a frame with origin "https://www.google.com" from accessing a cross-origin frame.

How to fix that? I disabled Django Recaptcha Ajax for now.

**Comment by AltusBarry** [comment]
recaptcha ajax is no longer supported.
