### ISSUE TITLE
Tests not working

### ISSUE THREAD

**Issue by donbalon4** [praekelt/django-recaptcha#184]
Hi.
I used to write my tests with `os.environ['RECAPTCHA_TESTING']` = 'True' ...` (like described in #150 )
This not work with the current version.
Is there a new way to do this?

**Comment by AltusBarry** [comment]
Hey @donbalon4 
The reliance on the environment variable was removed in version 1.5.0, we apologise for the inconvenience this may be causing you.

Assuming you want to test a form or form view response the `client.submit` method will need to be mocked, check out: https://github.com/praekelt/django-recaptcha/blob/develop/captcha/tests/test_fields.py#L25-L30 for an example of how we are now doing it.

**Comment by donbalon4** [comment]
Ohh, I see.
Thank you @AltusBarry :smiley: . I'll close this issue.

**Comment by AlviseSembenico** [comment]
Sorry, 
How to test a view and fake the captcha value? Thanks

**Comment by donbalon4** [comment]
@AlviseSembenico an example:

```from django.urls import reverse
from captcha.client import RecaptchaResponse
from unittest.mock import patch

@patch("captcha.fields.client.submit")
    def test_post_something(self, mocked_submit):
        mocked_submit.return_value = RecaptchaResponse(is_valid=True)
        response = self.client.post(
            reverse('something_url'),
            {
                'param_1': 'some1',
                'param_n': 'somen',
                'g-recaptcha-response': 'PASSED'
            },
            follow=True
        )
        self.assertEqual(response.status_code, 200)
        # some other asserts
```

**Comment by hoenie-ams** [comment]
How would that work with the ReCaptchaV3?

`captcha = fields.ReCaptchaField(widget=ReCaptchaV3)`

**Comment by plumber-craic** [comment]
@hoenie-ams did you figure out how to test with recaptchav3?

**Comment by hoenie-ams** [comment]
> @hoenie-ams did you figure out how to test with recaptchav3?

Nope, I used `ReCaptchaV2Invisible` instead.

**Comment by plumber-craic** [comment]
I'm still not great at tests, but was able to hack my v3 form inside the unit test like this:
```
    def test_outside_signin_ok(self):
        class CustomUserLoginFormWithoutCaptcha(CustomUserLoginForm):
            captcha = None
        OutsideView.login_form = CustomUserLoginFormWithoutCaptcha
```

Which I guess is not the correct way, but it lets my test pass, and lets captcha work outside of tests.

**Comment by donbalon4** [comment]
For those who are looking how to test other captcha versions, take a look to this code:

https://github.com/torchbox/django-recaptcha/tree/main/captcha/tests

**Comment by donbalon4** [comment]
Here's an example to test captcha v3 in version 3.0.0 of this app

```
from captcha.client import RecaptchaResponse
from unittest.mock import patch

@patch("captcha.client.submit")
    def test_post_something(self, mocked_submit):
        mocked_submit.return_value = RecaptchaResponse(
            is_valid=True,
            extra_data={'score': '1'}
        )
        response = self.client.post(
            reverse('something_url'),
            {
                'param_1': 'some1',
                'param_n': 'somen',
                'captcha': 'PASSED'
            },
            follow=True
        )
        self.assertEqual(response.status_code, 200)
        # some other asserts
```

**Comment by mrxsal** [comment]
> Here's an example to test captcha v3 in version 3.0.0 of this app
> 
> ```
> from captcha.client import RecaptchaResponse
> from unittest.mock import patch
> 
> @patch("captcha.client.submit")
> def test_post_something(self, mocked_submit):
>     mocked_submit.return_value = RecaptchaResponse(
>         is_valid=True,
>         extra_data={'score': '1'}
>     )
>     response = self.client.post(
>         reverse('something_url'),
>         {
>             'param_1': 'some1',
>             'param_n': 'somen',
>             'captcha': 'PASSED'
>         },
>         follow=True
>     )
>     self.assertEqual(response.status_code, 200)
>     # some other asserts
> ```

Thank you so much.
