### ISSUE TITLE
recaptcha v3 score

### ISSUE THREAD

**Issue by dominicmarmont** [praekelt/django-recaptcha#194]
recaptcha v3 has a `score` attribute on the response dict from recaptcha.

https://developers.google.com/recaptcha/docs/v3

It would me nice if we could have some way to access this score value from a successful response as it is googles quality score given to the user 0.0 being a bot and 1.0 being a human.

What do you think is the best way to make that accessible?

**Comment by VictorCarlquist** [comment]
Hi!

This MR #195 doesn't give access to the score value, but it can check if the captcha is valid (bot or human) based on the threshold value.

cheers!

**Comment by AltusBarry** [comment]
PR #195 has been merged and we have released version 2.0.5 into the wild. See the readme for a tad more info. https://github.com/praekelt/django-recaptcha#recaptcha-v3-score

**Comment by LuRsT** [comment]
I'm guessing we can close this Issue then :)
