### ISSUE TITLE
Problem with implementation (very basic)

### ISSUE THREAD

**Issue by GSnchez** [praekelt/django-recaptcha#225]
First of all I'm not a programmer. I can't make the app work. I want to implement it in my comments.

```
class CommentForm(forms.ModelForm):
    captcha = ReCaptchaField(widget=ReCaptchaV3())
    class Meta:
        model = Comment
        fields = ('name', 'body','captcha')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control mb-2', 'placeholder':'Nombre de usuario'}),
            'body': forms.CharField(widget=CKEditorUploadingWidget(attrs={'class': 'form-control'})),
        }
```

Got this on my forms, with the app on settings installed and the keys also in settings.py. Now I don't know how to continue. 

Thanks.

**Comment by princefishthrower** [comment]
@GSnchez - looks like you found out the issue. I am stuck, however. Like you I am using `forms.ModelForm`. What minimum score did you use here for V3?
