### ISSUE TITLE
Format of site key was invalid

### ISSUE THREAD

**Issue by nikolaygit** [praekelt/django-recaptcha#32]
After installing ```django-recaptcha 0.0.6```, adding the the keys as described in the ```README.rst``` and adding the recaptcha to a form:

```python
class MyForm(forms.ModelForm):
    captcha = ReCaptchaField(attrs={'theme' : 'clean'})
```

When I open the form template, the label "Captcha* is shown and the value of the field is "Input error: k: Format of site key was invalid".

How can I fix that?

Thanks you,

Nikolay

**Comment by adamchainz** [comment]
Improved the documentation in #114
