### ISSUE TITLE
How can I disable capcha on runtime?

### ISSUE THREAD

**Issue by sankalpanand** [praekelt/django-recaptcha#77]
I am keeping track of invalid user signin attempts. 
Initially, I don't want to show capcha. 
When the count reaches 3, I want to show capcha until he types a correct password.
I am keeping track of this count. 
I just want to know how to enable/disable this capcha at runtime.

Any help is greatly appreciated.
Thanks.

**Comment by dcramer** [comment]
@san89kalp https://github.com/getsentry/sentry/blob/master/src/sentry/web/forms/accounts.py#L27
