### ISSUE TITLE
Add support recaptcha v2

### ISSUE THREAD

**Issue by liminspace** [praekelt/django-recaptcha#79]
https://developers.google.com/recaptcha/intro

**Comment by Starefossen** [comment]
+1

**Comment by kevinmickey** [comment]
I think it is already supported -- see issue #63, PR #64, and docs at PR #67.

**Comment by AltusBarry** [comment]
This is indeed the case, it is supported as of v1.0.3, by adding _NOCAPTCHA = True_ to your settings.py
