### ISSUE TITLE
recaptcha render issue

### ISSUE THREAD

**Issue by serglopatin** [praekelt/django-recaptcha#83]
I'm using django-recaptcha-1.0.4
and noticed issue when rendering recaptcha (strange red line at the bottom)

![django_recaptcha_issue](https://cloud.githubusercontent.com/assets/12531923/10563367/6aba6f90-75ba-11e5-9acf-01d6d2676890.png)

you can also check here: http://review.food-singapore.com/restaurant/riders-cafe

**Comment by adamchainz** [comment]
I think this might be caused by the CSS on your page?

**Comment by serglopatin** [comment]
yes, you're right.. the css was broken..
I had some css classes like:
form.review ....

which caused this problem
