### ISSUE TITLE
Rename application to recaptcha

### ISSUE THREAD

**Issue by zenwalker** [praekelt/django-recaptcha#87]
Python package named as `django-recaptcha`, but application name is `captcha`. This is not obvious and creates collision with other captcha extensions, such as [django-simple-captcha](https://github.com/mbi/django-simple-captcha).

**Comment by hedleyroos** [comment]
Unfortunately there are existing installations and it would be too disruptive to rename it.

**Comment by zenwalker** [comment]
Release this feature in new major version and add upgrade guide to README. Major release is not to ensure backward compatibility. This does not affect existing installations.

**Comment by barseghyanartur** [comment]
@zenwalker:

It does not make sense. I have already proposed alternative names in both packages (to change to `simple_captcha` and `recaptcha`) to avoid collisions and I even think I wasn't the first one, but no - both devs were equally stubborn about it, saying that they are "the first" or "have more stars", blaming the other package, etc. In one of my packages I wanted to allow to use both, but finally ended up with this:

- https://github.com/barseghyanartur/django-fobi/blob/master/src/fobi/contrib/plugins/form_elements/security/captcha/fobi_form_elements.py
- https://github.com/barseghyanartur/django-fobi/blob/master/src/fobi/contrib/plugins/form_elements/security/recaptcha/fobi_form_elements.py

**Comment by tahajahangir** [comment]
The current solution is to use the another django-recaptcha module:
https://github.com/kbytesys/django-recaptcha2

**Comment by barseghyanartur** [comment]
@tahajahangir:

Is it based on this package just having the namespace issue fixed?

**Comment by tahajahangir** [comment]
@barseghyanartur  Yes, the `django-simple-captcha` is a way more complex than ReCaptcha integration, and doesn't have any viable alternative. But the `django-recaptcha2` has a similar functionality and seems to be a good alternative to this package.

**Comment by barseghyanartur** [comment]
Finally done in 4.0.0. :) https://github.com/torchbox/django-recaptcha/releases/tag/4.0.0
