### ISSUE TITLE
Django 1.8 support

### ISSUE THREAD

**Issue by dokterbob** [praekelt/django-recaptcha#88]
As part of the preparation of upgrading one of my projects to 1.8 LTS I'm considering each and every dependency and hence came across this one. I figured I might as well shoot out an issue for 1.8 support. 

Roughly the following needs to be done:

- [ ] Run tests on 1.8
- [ ] Fix any issues that might result
- [ ] Document supported Django and Python releases.

**Comment by powersjcb** [comment]
Testing addressed here -> [PR:102](https://github.com/praekelt/django-recaptcha/pull/102)

I haven't had any issues using 1.0.5 for django 1.9 and python3.5. (outside of the desire to use a settings rather than environment variables)

**Comment by adamchainz** [comment]
Django 1.8 is supported and tested on since #90 . Supported versions are now documented since #108 .
