### ISSUE TITLE
Bug with a mutable default argument in __init__ of ReCaptchaField

### ISSUE THREAD

**Issue by muffinresearch** [praekelt/django-recaptcha#91]
See https://github.com/praekelt/django-recaptcha/blob/develop/captcha/fields.py#L26

I was trying to figure out why when the lang attr is set the first time it gets stuck to whatever the first value is.  Then I found that subsequent calls to `client.display_html()` were being handled attrs with the lang key already set.

**Comment by muffinresearch** [comment]
Looks like you have a PR to fix this here: https://github.com/praekelt/django-recaptcha/pull/85

**Comment by adamchainz** [comment]
Fixed in #85.
